In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r'dataset.csv')
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [4]:
df = df.fillna("")
df['Symptom']=""
for i in range(1,18):
    df['s']=df["Symptom_{}".format(i)]
    df['Symptom']=df['Symptom']+df['s']

In [5]:
df.head(10)

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
5  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
6  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
7  Fungal infection     itching              skin_rash    dischromic _patches   
8  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
9  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches                                                     
1                                                                           
2                                                                           
3                                                                           
4                                                                           
5                                                                           
6                                                                           
7                                                                           
8                                                                           
9   dischromic _patches                                                     

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0                                                                     
1                                                                     
2                                                                     
3                                                                     
4                                                                     
5                                                                     
6                                                                     
7                                                                     
8                                                                     
9                                                                     

  Symptom_16 Symptom_17                                            Symptom s  
0                        itching skin_rash nodal_skin_eruptions dischro...    
1                         skin_rash nodal_skin_eruptions dischromic _pa...    
2                         itching nodal_skin_eruptions dischromic _patches    
3                                    itching skin_rash dischromic _patches    
4                                   itching skin_rash nodal_skin_eruptions    
5                         skin_rash nodal_skin_eruptions dischromic _pa...    
6                         itching nodal_skin_eruptions dischromic _patches    
7                                    itching skin_rash dischromic _patches    
8                                   itching skin_rash nodal_skin_eruptions    
9                        itching skin_rash nodal_skin_eruptions dischro...

Better than nulls i think

In [6]:
for i in range(1,18):
    df=df.drop("Symptom_{}".format(i),axis=1)
df=df.drop("s",axis=1)

In [7]:
df.head()

Disease                                            Symptom
0  Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
1  Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
2  Fungal infection   itching nodal_skin_eruptions dischromic _patches
3  Fungal infection              itching skin_rash dischromic _patches
4  Fungal infection             itching skin_rash nodal_skin_eruptions

In [9]:
df.to_csv(r'dataset.csv',index=False)

In [11]:
df[0:1].values

array([['Fungal infection',
        'itching skin_rash nodal_skin_eruptions dischromic _patches']],
      dtype=object)

In [12]:
df['Disease'].value_counts()

Disease
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Aller

#### 

In [13]:
X=df['Symptom']
y=df['Disease']

In [14]:
X.head(10)

0    itching skin_rash nodal_skin_eruptions dischro...
1     skin_rash nodal_skin_eruptions dischromic _pa...
2     itching nodal_skin_eruptions dischromic _patches
3                itching skin_rash dischromic _patches
4               itching skin_rash nodal_skin_eruptions
5     skin_rash nodal_skin_eruptions dischromic _pa...
6     itching nodal_skin_eruptions dischromic _patches
7                itching skin_rash dischromic _patches
8               itching skin_rash nodal_skin_eruptions
9    itching skin_rash nodal_skin_eruptions dischro...
Name: Symptom, dtype: object

In [15]:
y.head(10)

0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
5    Fungal infection
6    Fungal infection
7    Fungal infection
8    Fungal infection
9    Fungal infection
Name: Disease, dtype: object

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,shuffle=True,random_state=44)

In [17]:
y_train.head(10)

1057        Hepatitis E
4480           Migraine
2394    Osteoarthristis
4467          Psoriasis
3525           Impetigo
3038      Drug Reaction
4906          Pneumonia
4131     Hypothyroidism
1405             Dengue
3033           Impetigo
Name: Disease, dtype: object

In [18]:
print('Training Data Shape:', X_train.shape)
print('Testing Data Shape: ', X_test.shape)

Training Data Shape: (3690,)
Testing Data Shape:  (1230,)


In [19]:
y_train.value_counts()

Disease
Jaundice                                   98
Migraine                                   98
hepatitis A                                95
Heart attack                               95
Dimorphic hemmorhoids(piles)               95
Allergy                                    95
Hepatitis C                                93
Hepatitis D                                93
Typhoid                                    92
Gastroenteritis                            92
Pneumonia                                  92
Hypoglycemia                               92
Common Cold                                91
Tuberculosis                               91
Fungal infection                           91
Hepatitis E                                91
Arthritis                                  91
Psoriasis                                  91
Peptic ulcer diseae                        91
Malaria                                    90
Bronchial Asthma                           90
Dengue                    

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_train_tfidf.shape

(3690, 135)

In [20]:
pd.DataFrame(X_train_tfidf)[0]

0         (0, 107)\t0.42164632513477507\n  (0, 22)\t0....
1         (0, 124)\t0.4120490720427296\n  (0, 54)\t0.2...
2         (0, 79)\t0.4510419179046219\n  (0, 112)\t0.4...
3         (0, 51)\t0.45900352946016976\n  (0, 103)\t0....
4         (0, 131)\t0.5269244100190276\n  (0, 90)\t0.5...
                              ...                        
3685      (0, 67)\t0.5036364766736794\n  (0, 71)\t0.42...
3686      (0, 111)\t0.37930170238198424\n  (0, 65)\t0....
3687      (0, 87)\t0.6519490465239833\n  (0, 9)\t0.653...
3688      (0, 5)\t0.6339138832160964\n  (0, 128)\t0.65...
3689      (0, 39)\t0.556559575085783\n  (0, 82)\t0.556...
Name: 0, Length: 3690, dtype: object

In [21]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(X_train_tfidf,y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


LinearSVC()

In [22]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


In [23]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]


In [24]:
print(metrics.classification_report(y_test,predictions)) 

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic cholestasis       1.00      1.00      1.00        31
                            Common Cold       1.00      1.00      1.00        29
                           

In [25]:
print(metrics.accuracy_score(y_test,predictions))

1.0


In [26]:
ds=pd.read_csv(r'/kaggle/input/disease-symptom-description-dataset/symptom_Description.csv')
ds.head(10)

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/disease-symptom-description-dataset/symptom_Description.csv'

In [ ]:
ds.isnull().sum()

Disease        0
Description    0
dtype: int64

In [ ]:
ds.index=ds['Disease']
ds=ds.drop('Disease',axis=1)
ds.head(10)

Description
Disease                                                                                   
Drug Reaction                            An adverse drug reaction (ADR) is an injury ca...
Malaria                                  An infectious disease caused by protozoan para...
Allergy                                  An allergy is an immune system response to a f...
Hypothyroidism                           Hypothyroidism, also called underactive thyroi...
Psoriasis                                Psoriasis is a common skin disorder that forms...
GERD                                     Gastroesophageal reflux disease, or GERD, is a...
Chronic cholestasis                      Chronic cholestatic diseases, whether occurrin...
hepatitis A                              Hepatitis A is a highly contagious liver infec...
Osteoarthristis                          Osteoarthritis is the most common form of arth...
(vertigo) Paroymsal  Positional Vertigo  Benign paroxysmal positional vertigo (BPPV) is...

In [ ]:
pr=pd.read_csv(r'/kaggle/input/disease-symptom-description-dataset/symptom_precaution.csv')
pr.head(10)

Disease                      Precaution_1  \
0                            Drug Reaction                   stop irritation   
1                                  Malaria          Consult nearest hospital   
2                                  Allergy                    apply calamine   
3                           Hypothyroidism                     reduce stress   
4                                Psoriasis  wash hands with warm soapy water   
5                                     GERD            avoid fatty spicy food   
6                      Chronic cholestasis                        cold baths   
7                              hepatitis A          Consult nearest hospital   
8                          Osteoarthristis                     acetaminophen   
9  (vertigo) Paroymsal  Positional Vertigo                          lie down   

                    Precaution_2               Precaution_3  \
0       consult nearest hospital           stop taking drug   
1                avoid oily food         avoid non veg food   
2        cover area with bandage                        NaN   
3                       exercise                eat healthy   
4   stop bleeding using pressure             consult doctor   
5  avoid lying down after eating    maintain healthy weight   
6             anti itch medicine             consult doctor   
7             wash hands through     avoid fatty spicy food   
8       consult nearest hospital                  follow up   
9    avoid sudden change in body  avoid abrupt head movment   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths  
5                     exercise  
6                  eat healthy  
7                   medication  
8                   salt baths  
9                        relax

In [ ]:
pr.isnull().sum()

Disease         0
Precaution_1    0
Precaution_2    0
Precaution_3    1
Precaution_4    1
dtype: int64

In [ ]:
pr = pr.fillna("")
pr.head(10)

Disease                      Precaution_1  \
0                            Drug Reaction                   stop irritation   
1                                  Malaria          Consult nearest hospital   
2                                  Allergy                    apply calamine   
3                           Hypothyroidism                     reduce stress   
4                                Psoriasis  wash hands with warm soapy water   
5                                     GERD            avoid fatty spicy food   
6                      Chronic cholestasis                        cold baths   
7                              hepatitis A          Consult nearest hospital   
8                          Osteoarthristis                     acetaminophen   
9  (vertigo) Paroymsal  Positional Vertigo                          lie down   

                    Precaution_2               Precaution_3  \
0       consult nearest hospital           stop taking drug   
1                avoid oily food         avoid non veg food   
2        cover area with bandage                              
3                       exercise                eat healthy   
4   stop bleeding using pressure             consult doctor   
5  avoid lying down after eating    maintain healthy weight   
6             anti itch medicine             consult doctor   
7             wash hands through     avoid fatty spicy food   
8       consult nearest hospital                  follow up   
9    avoid sudden change in body  avoid abrupt head movment   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths  
5                     exercise  
6                  eat healthy  
7                   medication  
8                   salt baths  
9                        relax

In [ ]:
pr['precautions']=""
pr['punc']=', '
for i in range(1,5):
    pr['s']=pr["Precaution_{}".format(i)]+pr['punc']
    pr['precautions']=pr['precautions']+pr['s']
pr.head(10)

Disease                      Precaution_1  \
0                            Drug Reaction                   stop irritation   
1                                  Malaria          Consult nearest hospital   
2                                  Allergy                    apply calamine   
3                           Hypothyroidism                     reduce stress   
4                                Psoriasis  wash hands with warm soapy water   
5                                     GERD            avoid fatty spicy food   
6                      Chronic cholestasis                        cold baths   
7                              hepatitis A          Consult nearest hospital   
8                          Osteoarthristis                     acetaminophen   
9  (vertigo) Paroymsal  Positional Vertigo                          lie down   

                    Precaution_2               Precaution_3  \
0       consult nearest hospital           stop taking drug   
1                avoid oily food         avoid non veg food   
2        cover area with bandage                              
3                       exercise                eat healthy   
4   stop bleeding using pressure             consult doctor   
5  avoid lying down after eating    maintain healthy weight   
6             anti itch medicine             consult doctor   
7             wash hands through     avoid fatty spicy food   
8       consult nearest hospital                  follow up   
9    avoid sudden change in body  avoid abrupt head movment   

                  Precaution_4  \
0                    follow up   
1           keep mosquitos out   
2  use ice to compress itching   
3             get proper sleep   
4                   salt baths   
5                     exercise   
6                  eat healthy   
7                   medication   
8                   salt baths   
9                        relax   

                                         precautions punc  \
0  stop irritation, consult nearest hospital, sto...   ,    
1  Consult nearest hospital, avoid oily food, avo...   ,    
2  apply calamine, cover area with bandage, , use...   ,    
3  reduce stress, exercise, eat healthy, get prop...   ,    
4  wash hands with warm soapy water, stop bleedin...   ,    
5  avoid fatty spicy food, avoid lying down after...   ,    
6  cold baths, anti itch medicine, consult doctor...   ,    
7  Consult nearest hospital, wash hands through, ...   ,    
8  acetaminophen, consult nearest hospital, follo...   ,    
9  lie down, avoid sudden change in body, avoid a...   ,    

                               s  
0                    follow up,   
1           keep mosquitos out,   
2  use ice to compress itching,   
3             get proper sleep,   
4                   salt baths,   
5                     exercise,   
6                  eat healthy,   
7                   medication,   
8                   salt baths,   
9                        relax,

In [ ]:
for i in range(1,5):
    pr=pr.drop("Precaution_{}".format(i),axis=1)
pr.head(10) 

Disease  \
0                            Drug Reaction   
1                                  Malaria   
2                                  Allergy   
3                           Hypothyroidism   
4                                Psoriasis   
5                                     GERD   
6                      Chronic cholestasis   
7                              hepatitis A   
8                          Osteoarthristis   
9  (vertigo) Paroymsal  Positional Vertigo   

                                         precautions punc  \
0  stop irritation, consult nearest hospital, sto...   ,    
1  Consult nearest hospital, avoid oily food, avo...   ,    
2  apply calamine, cover area with bandage, , use...   ,    
3  reduce stress, exercise, eat healthy, get prop...   ,    
4  wash hands with warm soapy water, stop bleedin...   ,    
5  avoid fatty spicy food, avoid lying down after...   ,    
6  cold baths, anti itch medicine, consult doctor...   ,    
7  Consult nearest hospital, wash hands through, ...   ,    
8  acetaminophen, consult nearest hospital, follo...   ,    
9  lie down, avoid sudden change in body, avoid a...   ,    

                               s  
0                    follow up,   
1           keep mosquitos out,   
2  use ice to compress itching,   
3             get proper sleep,   
4                   salt baths,   
5                     exercise,   
6                  eat healthy,   
7                   medication,   
8                   salt baths,   
9                        relax,

In [ ]:
pr=pr.drop(['s','punc'],axis=1)
pr.head(10)

Disease  \
0                            Drug Reaction   
1                                  Malaria   
2                                  Allergy   
3                           Hypothyroidism   
4                                Psoriasis   
5                                     GERD   
6                      Chronic cholestasis   
7                              hepatitis A   
8                          Osteoarthristis   
9  (vertigo) Paroymsal  Positional Vertigo   

                                         precautions  
0  stop irritation, consult nearest hospital, sto...  
1  Consult nearest hospital, avoid oily food, avo...  
2  apply calamine, cover area with bandage, , use...  
3  reduce stress, exercise, eat healthy, get prop...  
4  wash hands with warm soapy water, stop bleedin...  
5  avoid fatty spicy food, avoid lying down after...  
6  cold baths, anti itch medicine, consult doctor...  
7  Consult nearest hospital, wash hands through, ...  
8  acetaminophen, consult nearest hospital, follo...  
9  lie down, avoid sudden change in body, avoid a...

In [ ]:
pr.index=pr['Disease']
pr=pr.drop('Disease',axis=1)
pr.head()

precautions
Disease                                                          
Drug Reaction   stop irritation, consult nearest hospital, sto...
Malaria         Consult nearest hospital, avoid oily food, avo...
Allergy         apply calamine, cover area with bandage, , use...
Hypothyroidism  reduce stress, exercise, eat healthy, get prop...
Psoriasis       wash hands with warm soapy water, stop bleedin...

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC  #model used Linear SVC+ Deepseek for report generation
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

# Step 1: Load and clean the data
data = pd.read_csv("dataset.csv")  # Replace with actual path
data.columns = ['Disease', 'Symptom']

# Normalize text
data['Symptom'] = data['Symptom'].str.replace("_", " ").str.replace("  ", " ").str.lower().str.strip()
data['Disease'] = data['Disease'].str.strip()

# Combine all symptoms for same disease (optional but improves consistency)
grouped = data.groupby('Symptom')['Disease'].agg(lambda x: x.mode()[0]).reset_index()

# Step 2: Split data
X = grouped['Symptom']
y = grouped['Disease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Create Pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LinearSVC())
])

# Step 4: Train model
pipeline.fit(X_train, y_train)

# Step 5: Evaluate
y_pred = pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

# Step 6: Prediction function
def predict_disease(symptom_input):
    symptom_input = symptom_input.lower().replace("_", " ").strip()
    return pipeline.predict([symptom_input])[0]

# Example use
print(predict_disease("vomiting sweating chest_pain"))


                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         2
                                   Acne       1.00      1.00      1.00         2
                    Alcoholic hepatitis       1.00      1.00      1.00         2
                              Arthritis       1.00      1.00      1.00         1
                       Bronchial Asthma       1.00      1.00      1.00         3
                            Chicken pox       1.00      1.00      1.00         2
                    Chronic cholestasis       1.00      1.00      1.00         1
                            Common Cold       1.00      1.00      1.00         1
                                 Dengue       1.00      1.00      1.00         1
                               Diabetes       1.00      1.00      1.00         3
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00         2
                          D

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


In [26]:
import joblib

In [27]:
joblib.dump(pipeline, 'disease_prediction_model.joblib')

['disease_prediction_model.joblib']